api_version = "2024-04"

[[extensions]]
name = "t:name"
handle = "loyalty-points-action"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/ActionExtension.tsx"
# The target must match the target used in the module file (./src/ActionExtension.jsx)
target = "admin.customer-segment-details.action.render"
